# Generated by Django 2.0.5 on 2018-06-06 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_therapist'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='therapist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clients.Therapist'),
            preserve_default=False,
        ),
    ]
